apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres/
  - configmap.yaml
  - app-secret.yaml
  - deployment.yaml
  - service.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: simpleapp-api
      app.kubernetes.io/component: api
      app.kubernetes.io/managed-by: argocd
