apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simpleapp-dev

resources:
- ../../base
- namespace.yaml

labels:
- includeSelectors: true
  pairs:
    environment: dev

images:
- name: simpleapp-api
  newName: ghcr.io/atychkivskyy/simpleapp-api
  newTag: f8cd3c9

replicas:
- count: 1
  name: simpleapp-api

patches:
- patch: |-
    - op: replace
      path: /data/APP_ENVIRONMENT
      value: "dev"
  target:
    kind: ConfigMap
    name: simpleapp-config
