apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simpleapp-staging

resources:
- ../../base
- namespace.yaml

labels:
- includeSelectors: true
  pairs:
    environment: staging

images:
- name: simpleapp-api
  newName: ghcr.io/atychkivskyy/simpleapp-api
  newTag: 16d2768

replicas:
- count: 2
  name: simpleapp-api

patches:
- patch: |-
    - op: replace
      path: /data/APP_ENVIRONMENT
      value: "staging"
  target:
    kind: ConfigMap
    name: simpleapp-config
